### ISSUE TITLE
in server,how to generate /etc/ssl/cert.pem file?

### ISSUE THREAD

**Issue by luckypoem** [tagattie/Unbound-DNSSEC-DNS-over-TLS#1]
i saw https://github.com/tagattie/Unbound-DNSSEC-DNS-over-TLS/blob/master/unbound.conf ,but in server,how to generate /etc/ssl/cert.pem file?tks

**Comment by tagattie** [comment]
Install `security/ca_root_nss` from packages (or ports), e.g.

```
pkg install ca_root_nss
```

That creates `/etc/ssl/cert.pem`, which is actually a symbolic link to `/usr/local/share/certs/ca-root-nss.crt.

**Comment by luckypoem** [comment]
hi.

my vps is centos7 
[root@host ~]# yum install ca-certificates -y
Package ca-certificates-2018.2.22-70.0.el7_5.noarch already installed and latest version
Nothing to do
[root@host ~]#

since i already have ca-certificates installed on my linux vps, now how to generate /etc/ssl/cert.pem file by using ca-certificates?

**Comment by tagattie** [comment]
If you have already installed the ca-certificates package, just replacing `/etc/ssl/cert.pem` with `/etc/pki/tls/cert.pem` in the configuration file would be enough. (I presume running an unbound server on FreeBSD. CentOS installes the root certificate to a different location.)

cf. https://serverfault.com/a/722646
